language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y valgrind expat fop xsltproc
script:
 - cd gpsbabel ; ./configure && make -j3 all && make gui &&  make doc && bash ./testo  && bash ./vtesto
# TODO: build mac, test-all
