language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y valgrind
script:
 - cd gpsbabel ; ./configure && make -j3  && bash ./testo  && bash ./vtesto
# TODO: build doc, GUI, mac
