version: 1.0.{build}

environment:
  matrix:
  # MinGW
  - name: win32
    platform: mingw
    qt: 5.5\mingw492_32
    tools: mingw492_32
  # MinGW
  - name: win32
    platform: mingw
    qt: 5.6\mingw49_32
    tools: mingw492_32
  # MinGW
  #  - name: win32
  #    platform: mingw
  #    qt: 5.9\mingw53_32
  #    tools: mingw530_32
  # MSVC x32
  - name: win32
    platform: x86
    qt: 5.6\msvc2015
  # MSVC x64
  - name: win64
    platform: amd64
    qt: 5.6\msvc2015_64

init:
  - if %platform%==mingw set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if %platform%==mingw set PATH=C:\Qt\Tools\%tools%\bin;%PATH%
  - set PATH=C:\Qt\%qt%\bin;%PATH%
  - if not %platform%==mingw call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%

# Flesh out with amd64/msvc cases later.
build_script:
  - ps: |
      if (($env:platform -eq "mingw") -and ($env:qt -eq "5.5\mingw492_32"))
      {
        Get-Location
        qmake -query
        # mimic creator shadow build to match Inno setup file
        New-Item ..\build-GPSBabel-Desktop_Qt_5_5_1_Mingw_32bit-Release -type directory -force
        cd ..\build-GPSBabel-Desktop_Qt_5_5_1_Mingw_32bit-Release
        qmake ..\gpsbabel\GPSBabel.pro -spec win32-g++
        mingw32-make qmake_all
        mingw32-make
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
        # copy GPSBabel.exe for use by test_script
        New-Item ..\gpsbabel\release -type directory -force
        Copy-Item release\GPSBabel.exe ..\gpsbabel\release\GPSBabel.exe
        cd ..\gpsbabel
        New-Item build-app-Desktop_Qt_5_5_1_MinGW_32bit-Release -type directory -force
        cd build-app-Desktop_Qt_5_5_1_MinGW_32bit-Release
        qmake ..\gui\app.pro -spec win32-g++
        mingw32-make qmake_all
        mingw32-make
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
        lupdate ..\gui\app.pro
        lrelease ..\gui\app.pro
        # windeployqt in 5.5.1 suffers from bug
        # https://bugreports.qt.io/browser/QTBUG-48946
        # which trashes the translations.  Work around
        # by using the next version of windeployqt which had this
        # bug fixed.
        # use --plugindir option to locate the plugins.
        C:\Qt\5.6\mingw49_32\bin\windeployqt.exe --verbose 10 --plugindir release\plugins release\GPSBabelFE.exe
        & 'C:\Program Files (x86)\Inno Setup 5\ISCC.exe' ..\gui\setup.iss
        cd ..
        $sha=(git rev-parse --short HEAD)
        Get-ChildItem .\gui\release\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName "GPSBabelTest-$($env:APPVEYOR_BUILD_VERSION)-$($sha).exe" }
      }
      elseif ($env:platform -eq "mingw")
      {
        qmake GPSBabel.pro
        mingw32-make
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
      }
      else
      {
        qmake GPSBabel.pro
        nmake
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
      }
      # work around issue with standard error output causing a build failure by making sure last command succeeds.
      # see https://help.appveyor.com/discussions/problems/10014-false-build-fail-status
      Write-Host "Finished build_script"

test_script:
  - ps: |
      $env:projdir=(C:\msys64\usr\bin\bash.exe -c "pwd")
      C:\msys64\usr\bin\bash.exe -lc "echo $env:projdir"
      # work around issue with standard error output from xmllint causing a build failure by redirecting stderr.
      # in this case making sure the last command succeeds is not sufficient.
      # see https://help.appveyor.com/discussions/problems/10014-false-build-fail-status
      C:\msys64\usr\bin\bash.exe -lc "cd $env:projdir; PNAME=./release/GPSBabel.exe GBTEMP=./gbtemp ./testo 2>&1"
      Write-Host "Finished test_script with exit status $LastExitCode"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
